[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 3
solc-version = "0.8.24"
evm_version = "paris"
via_ir = true
fs_permissions = [{ access = "read-write", path = "./deployments/"}, { access = "read-write", path = "./facets/"}, { access = "read-write", path = "./data/"}, { access = "read", path = "./constants/"}]
memory_limit = 17179869184


[fmt]
sort_imports = true
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
